In [2]:
from transformers import BartTokenizer, BartModel,BartForConditionalGeneration
import pandas as pd
from datasets import load_metric
import torch
from torch.utils.data import Dataset
from transformers import  Seq2SeqTrainingArguments, Seq2SeqTrainer,DataCollatorForSeq2Seq
metric = load_metric("rouge")

<ipython-input-2-333f30692099>:7: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("rouge")


In [3]:
from utils import PoemDataset,encode_sentences

In [3]:
# Download Model 
# use checkpoint at 34000 iterations

In [53]:
ls

'=20.9'           __init__.py    data_processing.ipynb   utils.py
 BART-GAN.ipynb   __pycache__/   data_raw/
 GAN_models/      data/          finetuned_bart.ipynb


In [54]:
tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')
model = BartForConditionalGeneration.from_pretrained('BART-base/checkpoint-25000')



#last_hidden_states = outputs.last_hidden_state

In [181]:
generated_str, probs = simple_decoding(model,inputs)
print(' '.join(tokenizer.batch_decode(generated_str)))

<ipython-input-178-0b7b6bf5747b>:30: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  output_tokens = torch.cat([output_tokens,torch.tensor(next_word)],axis=1)


<pad> <s>  i  have  a  card 
 held  in  my  hand  and  i  dont 
 even  know  what  it  is </s>


In [153]:
def prepare_inputs_for_generation(input_ids, past=None, attention_mask=None, use_cache=None, **kwargs):
    # if model is used as a decoder in encoder-decoder model, the decoder attention mask is created on the fly
    if attention_mask is None:
        attention_mask = input_ids.new_ones(input_ids.shape)

    if past:
        input_ids = input_ids[:, -1:]
    # first step, decoder_cached_states are empty
    return {
        "input_ids": input_ids,  # encoder_outputs is defined. input_ids not needed
        "attention_mask": attention_mask,
        "past_key_values": past,
        "use_cache": use_cache,
    }

In [154]:
logits_processor = LogitsProcessorList(
      [
            MinLengthLogitsProcessor(10, eos_token_id=model.config.eos_token_id),
        ]
      )

In [156]:

complex_decoder(model.cpu(),inputs)

tensor([[    0, 11706,  1886, 50264,     2]])
tensor([[    0, 11706,  1886, 50264,     2, 50118]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,

tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     

KeyboardInterrupt: 

In [20]:
input_ids

tensor([[1026, 1244,  307, 1744,  284]])

# Retreive data
Right now just using kaggle corpus

In [67]:
pwd

'/home/alexander/nlg-project/data'

In [5]:
processed_data_dir = '/home/alexander/nlg-project/data/'

In [128]:
train_df['Poem'][1]

'ive actually\nheld a black card in my hand\nand cant believe it'

In [54]:
test_df = pd.read_csv(processed_data_dir + 'test_data.csv')
train_df = pd.read_csv(processed_data_dir + 'train_data.csv')
print(train_df)


        Unnamed: 0                                               Poem  \
0             7542  the mockingbird has testified\nto springs exis...   
1           116211  ive actually\nheld a black card in my hand\nan...   
2            31718  although alas the\ncoat on his back is a coat\...   
3            97130  these memories dont\nmean anything to you and\...   
4            97063  a mad old lady\nwhooped her tits out at me in\...   
...            ...                                                ...   
136820      133722  the manager hugged\nme like u back see i am\na...   
136821       50010  an entire plot\nbased around klaus tripping an...   
136822       96222  why cant paulina\nhave social media i\nmiss he...   
136823        5797  i feel used he said\nand old as usual\ni belie...   
136824       51245  tip if youre upset\ntake a walk or jog it off\...   

                   Title  
0       testified almond  
1              held card  
2        lining although  
3          memo

NameError: name 'model_input' is not defined

In [1]:
train_model = encode_sentences(tokenizer,train_df)
test_model = encode_sentences(tokenizer,test_df)

NameError: name 'encode_sentences' is not defined

In [61]:
test_model

{'input_ids': tensor([[    0,  2841, 47320,  ...,     1,     1,     1],
         [    0,    70,   254,  ...,     1,     1,     1],
         [    0,  2649,  3006,  ...,     1,     1,     1],
         ...,
         [    0, 17668,  6148,  ...,     1,     1,     1],
         [    0, 13789,  7252,  ...,     1,     1,     1],
         [    0, 16328,  9699,  ...,     1,     1,     1]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]]),
 'labels': tensor([[    0,   608,    24,  ...,     1,     1,     1],
         [    0,  4356,  1158,  ...,     1,     1,     1],
         [    0, 17271,  2892,  ...,     1,     1,     1],
         ...,
         [    0,  7409,    10,  ...,     1,     1,     1],
         [    0,  7252,    37,  ...,     1,     1,     1],
         [    0,   141,   171,  ...,     1,     1,    

In [57]:
train_ds = PoemDataset(train_model)
eval_ds = PoemDataset(test_model)

In [ ]:
class PoemDataset(Dataset):
    def __init__(self, df):
        self.labels = df['labels']
        self.mask = df['attention_mask']
        self.input = df['input_ids']
        #self.target_transform = target_transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        
        input_ids = self.input[idx]
        attention_masks = self.mask[idx]
        target_ids = self.labels[idx]
        batch = {
          "input_ids": input_ids,
          "decoder_attention_mask": torch.tensor([1] * 128),
          "attention_mask": attention_masks,
          "label_ids": target_ids,
        }
        return batch

In [ ]:
class Collator_poem_gen(DataCollatorForSeq2Seq):
        
    def __call__(self, batch):
        input_ids_batch = []
        input_ids_len = []
        
        labels_batch = []
        labels_len = []
        
        for example in batch:
            input_ids = example["Title"]
            input_ids_len.append(len(input_ids))
            input_ids_batch.append(input_ids)
            
            labels = example["Poem"]
            labels_len.append(len(labels))
            labels_batch.append(labels)

        input_ids_padded = self.process_encoded_text(input_ids_batch, input_ids_len, self.tokenizer.pad_token_id)
        labels_padded = self.process_encoded_text(labels_batch, labels_len, self.label_pad_token_id)
        
        attention_mask = self.generate_attention_mask(input_ids_padded, self.tokenizer.pad_token_id)
        decoder_attention_mask = self.generate_attention_mask(labels_padded, self.tokenizer.pad_token_id)
        
        return {
            "input_ids": input_ids_padded,
            "attention_mask": attention_mask,
            "decoder_attention_mask": decoder_attention_mask,
            "labels": labels_padded,
        }

    def process_encoded_text(self, sequences, sequences_len, pad_token_id):
        sequences_max_len = np.max(sequences_len)
        max_length = min(sequences_max_len, self.max_length)
        padded_sequences = self.pad_sequences(sequences, max_length, pad_token_id)
        return torch.LongTensor(padded_sequences)

    def generate_attention_mask(self, input_ids, pad_token_id):
        return (input_ids != pad_token_id).long()
    
    def pad_sequences(self, sequences, max_length, pad_token_id):
        num_samples = len(sequences)
        padded_sequences = np.full((num_samples, max_length), pad_token_id)
        for i, sequence in enumerate(sequences):
            sequence = np.array(sequence)[:max_length]
            padded_sequences[i, :len(sequence)] = sequence
        return padded_sequences

In [99]:
from sklearn.model_selection import train_test_split

input_df = pd.DataFrame.from_dict(model_input)

ValueError: If using all scalar values, you must pass an index

In [65]:
batch_size = 16 

args = Seq2SeqTrainingArguments(
    "BART-base",
    evaluation_strategy = "epoch",
    #learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
   # weight_decay=0.01,
   # save_total_limit=3,
   # num_train_epochs=1,
   # predict_with_generate=True,
    
    learning_rate=1e-4,
    weight_decay=0.01,
    adam_beta1=0.9,
    adam_beta2=0.999,
    adam_epsilon=1e-6,
    max_grad_norm=1.0,
    num_train_epochs=10,
    lr_scheduler_type="linear",
    warmup_ratio=0.1,
   # label_names="labels",
    #fp16=True,
  #  use_auth_token=False
    #push_to_hub=True,
)

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [66]:
#data_collator = Collator_poem_gen(tokenizer=tokenizer, max_length=512)
#train_ds = PoemDataset(model_input)
#eval_ds = PoemDataset(model_input)
trainer = Seq2SeqTrainer(
    model=model,
    args=args,
   # data_collator=data_collator,
    train_dataset=train_ds,
    
    eval_dataset=eval_ds,
    #use_auth_token=False,
    
    tokenizer=tokenizer
)

In [94]:
trainer

In [95]:
#!python -c "from huggingface_hub.hf_api import HfFolder; HfFolder.save_token('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')"


In [67]:
trainer.train()

/home/alexander/anaconda3/lib/python3.8/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 136825
  Num Epochs = 10
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 85520


Saving model checkpoint to BART-base/checkpoint-500
Configuration saved in BART-base/checkpoint-500/config.json
Model weights saved in BART-base/checkpoint-500/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-500/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-500/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-1000
Configuration saved in BART-base/checkpoint-1000/config.json
Model weights saved in BART-base/checkpoint-1000/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-1000/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-1000/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-1500
Configuration saved in BART-base/checkpoint-1500/config.json
Model weights saved in BART-base/checkpoint-1500/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-1500/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-1500/special_toke

Saving model checkpoint to BART-base/checkpoint-13000
Configuration saved in BART-base/checkpoint-13000/config.json
Model weights saved in BART-base/checkpoint-13000/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-13000/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-13000/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-13500
Configuration saved in BART-base/checkpoint-13500/config.json
Model weights saved in BART-base/checkpoint-13500/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-13500/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-13500/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-14000
Configuration saved in BART-base/checkpoint-14000/config.json
Model weights saved in BART-base/checkpoint-14000/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-14000/tokenizer_config.json
Special tokens file saved in BART-base/checkpoin

Special tokens file saved in BART-base/checkpoint-28000/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-28500
Configuration saved in BART-base/checkpoint-28500/config.json
Model weights saved in BART-base/checkpoint-28500/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-28500/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-28500/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-29000
Configuration saved in BART-base/checkpoint-29000/config.json
Model weights saved in BART-base/checkpoint-29000/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-29000/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-29000/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-29500
Configuration saved in BART-base/checkpoint-29500/config.json
Model weights saved in BART-base/checkpoint-29500/pytorch_model.bin
tokenizer config file saved in BART-base/checkpo

tokenizer config file saved in BART-base/checkpoint-40000/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-40000/special_tokens_map.json
IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

Saving model checkpoint to BART-base/checkpoint-48500
Configuration saved in BART-base/checkpoint-48500/config.json
Model weights saved in BART-base/checkpoint-48500/pytorch_model.bin
tokenizer config file saved in BART-base/checkpoint-48500/tokenizer_config.json
Special tokens file saved in BART-base/checkpoint-48500/special_tokens_map.json
Saving model checkpoint to BART-base/checkpoint-49000
Configuration saved in BART-base/checkpoint-49000/config.json
Model weights saved in BART-base/checkpoint-49000/pytor

KeyboardInterrupt: 

In [68]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 7202
  Batch size = 16


{'eval_loss': 0.4164099395275116}

In [16]:
trainer.plot()

AttributeError: 'Seq2SeqTrainer' object has no attribute 'plot'