In [1]:
from transformers import BartTokenizer, BartModel,BartForConditionalGeneration
import pandas as pd
from datasets import load_metric
import torch
from torch.utils.data import Dataset
from transformers import  Seq2SeqTrainingArguments, Seq2SeqTrainer,DataCollatorForSeq2Seq
metric = load_metric("rouge")

<ipython-input-1-333f30692099>:7: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("rouge")


In [2]:
from utils import PoemDataset,encode_sentences

In [3]:
# Download Model 
# use checkpoint at 34000 iterations

In [53]:
ls

'=20.9'           __init__.py    data_processing.ipynb   utils.py
 BART-GAN.ipynb   __pycache__/   data_raw/
 GAN_models/      data/          finetuned_bart.ipynb


In [3]:
tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')
model = BartForConditionalGeneration.from_pretrained('facebook/bart-base')

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

#last_hidden_states = outputs.last_hidden_state

In [3]:
inputs = tokenizer("held card", return_tensors="pt")
inputs = inputs 

#inputs['input_ids'][:,-1]= 0
#inputs['input_ids'] = torch.cat([inputs['input_ids'],torch.tensor([50264]).unsqueeze(0)],axis=1)
#inputs['attention_mask'] = torch.cat([inputs['attention_mask'],torch.tensor([1]).unsqueeze(0)],axis=1)
inputs

{'input_ids': tensor([[    0, 11706,  1886,     2]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [55]:
model

BartForConditionalGeneration(
  (model): BartModel(
    (shared): Embedding(50265, 768, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): Embedding(50265, 768, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 768)
      (layers): ModuleList(
        (0): BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=768, out_features=768, bias=True)
            (v_proj): Linear(in_features=768, out_features=768, bias=True)
            (q_proj): Linear(in_features=768, out_features=768, bias=True)
            (out_proj): Linear(in_features=768, out_features=768, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=768, out_features=3072, bias=True)
          (fc2): Linear(in_features=3072, out_features=768, bias=True)
          (final_layer_norm): LayerNorm((768,), eps=1e-05,

In [177]:
out = torch.argmax(model(**inputs).logits[:, :, :],axis=-1)
out.shape

torch.Size([1, 5])

In [82]:
model.config

BartConfig {
  "_name_or_path": "BART-base/checkpoint-25000",
  "activation_dropout": 0.1,
  "activation_function": "gelu",
  "add_bias_logits": false,
  "add_final_layer_norm": false,
  "architectures": [
    "BartForConditionalGeneration"
  ],
  "attention_dropout": 0.1,
  "bos_token_id": 0,
  "classif_dropout": 0.1,
  "classifier_dropout": 0.0,
  "d_model": 768,
  "decoder_attention_heads": 12,
  "decoder_ffn_dim": 3072,
  "decoder_layerdrop": 0.0,
  "decoder_layers": 6,
  "decoder_start_token_id": 2,
  "dropout": 0.1,
  "early_stopping": true,
  "encoder_attention_heads": 12,
  "encoder_ffn_dim": 3072,
  "encoder_layerdrop": 0.0,
  "encoder_layers": 6,
  "eos_token_id": 2,
  "forced_bos_token_id": 0,
  "forced_eos_token_id": 2,
  "gradient_checkpointing": false,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2"
  },
  "init_std": 0.02,
  "is_encoder_decoder": true,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_2": 2
  },
  "max_position_emb

In [102]:
model(inputs['input_ids']).logits.shape

torch.Size([1, 4, 50265])

In [155]:
#this fucking works thank god

output_tokens = torch.tensor([1]).type(torch.LongTensor)
output_tokens = output_tokens.unsqueeze(0)
#print(output_tokens.shape)
#output_tokens = torch.long(output_tokens)
eos = 2
done = False
while not done:
    encoder_hidden_state = model.model.encoder(inputs['input_ids']).last_hidden_state
   # print(encoder_hidden_state)
    last_hidden = model.model.decoder(input_ids=output_tokens,
            encoder_hidden_states=encoder_hidden_state,
            encoder_attention_mask=inputs['attention_mask'])
    #logits = model.decoder(inputs['input_ids'])
   # logits = model.lm_head(last_hidden)[0][0]
    #print(logits[1:])
    #print(model.lm_head)
    lm_logits = model.lm_head(last_hidden[0])
    lm_logits = lm_logits + model.final_logits_bias
    
    lm_logits = lm_logits.squeeze()
    
    lm_logits = lm_logits[-1]
  #  print(lm_logits)
   # logits = logits[1:]
    next_word = lm_logits.argmax().unsqueeze(0).unsqueeze(0)
  #  print(next_word.shape)
    #output_tokens.append(next_word)
   # print(output_tokens.shape)
    output_tokens = torch.cat([output_tokens,torch.tensor(next_word)],axis=1)
   # print(output_tokens.shape)
    print(output_tokens)
    if next_word == eos: break

<ipython-input-155-ce5e4363f521>:31: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  output_tokens = torch.cat([output_tokens,torch.tensor(next_word)],axis=1)


tensor([[1, 0]])
tensor([[  1,   0, 939]])
tensor([[  1,   0, 939,  33]])
tensor([[  1,   0, 939,  33,  10]])
tensor([[   1,    0,  939,   33,   10, 1886]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127,
           865]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127,
           865,     8]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127,
           865,     8,   939]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127,
           865,     8,   939, 33976]])
tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127,
           865,     8,   939, 33976, 50118]])
tensor

In [114]:
tokenizer.batch_decode(output_tokens)

['<pad><s> i have a card\nheld in my hand and i dont\neven know what it is</s>']

In [168]:
inputs['input_ids'] = torch.cat([inputs['input_ids'],out.unsqueeze(0)],axis=1)
inputs['attention_mask'] = torch.cat([inputs['attention_mask'],torch.tensor([1]).unsqueeze(0)],axis=1)

RuntimeError: Tensors must have same number of dimensions: got 2 and 3

In [151]:
inputs['input_ids']

tensor([[    0, 11706,  1886, 50264,     2]])

In [169]:
tokenizer.batch_decode(model.eval().cpu().generate(inputs['input_ids'],attention_mask=inputs["attention_mask"],max_length=128, use_cache=False,
        decoder_start_token_id = tokenizer.pad_token_id,
        num_beams= 1,
        early_stopping = True))

['<pad><s> i have a card\nheld in my hand and i dont\neven know what it is</s>']

In [170]:
model.eval().cpu().generate(inputs['input_ids'],attention_mask=inputs["attention_mask"],max_length=128, use_cache=False,
        decoder_start_token_id = tokenizer.pad_token_id,
        num_beams= 1,
        early_stopping = False)

tensor([[    1,     0,   939,    33,    10,  1886, 50118, 11706,    11,   127,
           865,     8,   939, 33976, 50118, 12963,   216,    99,    24,    16,
             2]])

In [178]:
#note the argmx does get
#this is greedy
def simple_decoding(model,inputs):
    logprobs = []
    output_tokens = torch.tensor([1]).type(torch.LongTensor)
    output_tokens = output_tokens.unsqueeze(0)
    eos = 2
    done = False
    while not done:
        encoder_hidden_state = model.model.encoder(inputs['input_ids']).last_hidden_state
        last_hidden = model.model.decoder(input_ids=output_tokens,
                encoder_hidden_states=encoder_hidden_state,
                encoder_attention_mask=inputs['attention_mask'])
        lm_logits = model.lm_head(last_hidden[0])
        lm_logits = lm_logits + model.final_logits_bias
        
        lm_logits = lm_logits.squeeze()
       # print(lm_logits.shape)
        lm_logits = lm_logits[-1]
        next_word = lm_logits.argmax().unsqueeze(0).unsqueeze(0)
        
        try:
            logprobs.append(lm_logits[next_word].squeeze())
        except:
            logprobs = [lm_logits]
        output_tokens = torch.cat([output_tokens,torch.tensor(next_word)],axis=1)
       # print(output_tokens.shape)
       # print(output_tokens)
        if next_word == eos: break
    return output_tokens.squeeze(),logprobs
            

In [181]:
generated_str, probs = simple_decoding(model,inputs)
print(' '.join(tokenizer.batch_decode(generated_str)))

<ipython-input-178-0b7b6bf5747b>:30: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  output_tokens = torch.cat([output_tokens,torch.tensor(next_word)],axis=1)


<pad> <s>  i  have  a  card 
 held  in  my  hand  and  i  dont 
 even  know  what  it  is </s>


In [153]:
def prepare_inputs_for_generation(input_ids, past=None, attention_mask=None, use_cache=None, **kwargs):
    # if model is used as a decoder in encoder-decoder model, the decoder attention mask is created on the fly
    if attention_mask is None:
        attention_mask = input_ids.new_ones(input_ids.shape)

    if past:
        input_ids = input_ids[:, -1:]
    # first step, decoder_cached_states are empty
    return {
        "input_ids": input_ids,  # encoder_outputs is defined. input_ids not needed
        "attention_mask": attention_mask,
        "past_key_values": past,
        "use_cache": use_cache,
    }

In [154]:
logits_processor = LogitsProcessorList(
      [
            MinLengthLogitsProcessor(10, eos_token_id=model.config.eos_token_id),
        ]
      )

In [155]:
def complex_decoder(model,inputs):
    device = 'cpu'
    input_ids = inputs['input_ids']
    scores = () 
    output_attentions = False
    return_dict_in_generate = True
    output_hidden_states = False
    eos_token_id = 2 #i hope
    pad_token_id = 1
    scores = ()
    output_scores = True
    unfinished_sequences = input_ids.new(input_ids.shape[0]).fill_(1)

    this_peer_finished = False  # used by synced_gpus only
    while True:

        print(input_ids)
        # prepare model inputs
        model_inputs = prepare_inputs_for_generation(input_ids)#, **model_kwargs)

        # forward pass to get next token
        outputs = model(
            **model_inputs,
            return_dict=True,
            output_attentions=True,
            output_hidden_states=True,
        )


        next_token_logits = outputs.logits[:, -1, :]

        # pre-process distribution
        next_tokens_scores = logits_processor(input_ids, next_token_logits)

        # Store scores, attentions and hidden_states when required
        if return_dict_in_generate:
            if output_scores:
                scores += (next_tokens_scores,)
            if output_attentions:
                decoder_attentions += (
                    (outputs.decoder_attentions,) if self.config.is_encoder_decoder else (outputs.attentions,)
                )
                if self.config.is_encoder_decoder:
                    cross_attentions += (outputs.cross_attentions,)

            if output_hidden_states:
                decoder_hidden_states += (
                    (outputs.decoder_hidden_states,)
                    if self.config.is_encoder_decoder
                    else (outputs.hidden_states,)
                )

        # argmax
        next_tokens = torch.argmax(next_tokens_scores, dim=-1)

        # finished sentences should have their next token be a padding token
        if eos_token_id is not None:
            if pad_token_id is None:
                raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")
            next_tokens = next_tokens * unfinished_sequences + pad_token_id * (1 - unfinished_sequences)

        # update generated ids, model inputs, and length for next step
        input_ids = torch.cat([input_ids, next_tokens[:, None]], dim=-1)
       # model_kwargs = self._update_model_kwargs_for_generation(
       #     outputs, model_kwargs, is_encoder_decoder=self.config.is_encoder_decoder
       # )

        # if eos_token was found in one sentence, set sentence to finished
        if eos_token_id is not None:
            unfinished_sequences = unfinished_sequences.mul((next_tokens != eos_token_id).long())

        # stop when each sentence is finished, or if we exceed the maximum length
        if unfinished_sequences.max() == 0:

            break



In [156]:

complex_decoder(model.cpu(),inputs)

tensor([[    0, 11706,  1886, 50264,     2]])
tensor([[    0, 11706,  1886, 50264,     2, 50118]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,

tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1]])
tensor([[    0, 11706,  1886, 50264,     2, 50118,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     

KeyboardInterrupt: 

In [30]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
   LogitsProcessorList,
       MinLengthLogitsProcessor,
           StoppingCriteriaList,
            MaxLengthCriteria,
         )

tokenizer_g = AutoTokenizer.from_pretrained("gpt2")
model_g = AutoModelForCausalLM.from_pretrained("gpt2")
model_g.config.pad_token_id = model.config.eos_token_id
input_prompt = "It might be possible to"
input_ids = tokenizer(input_prompt, return_tensors="pt")#.input_ids
    
logits_processor = LogitsProcessorList(
      [
            MinLengthLogitsProcessor(10, eos_token_id=model_g.config.eos_token_id),
        ]
      )
stopping_criteria = StoppingCriteriaList([MaxLengthCriteria(max_length=20)])
outputs = model.greedy_search(
         **input_ids, logits_processor=logits_processor, stopping_criteria=stopping_criteria
        )
tokenizer.batch_decode(outputs, skip_special_tokens=True)

ValueError: You have to specify either input_ids or inputs_embeds

In [20]:
input_ids

tensor([[1026, 1244,  307, 1744,  284]])

# Retreive data
Right now just using kaggle corpus

In [67]:
pwd

'/home/alexander/nlg-project/data'

In [4]:
processed_data_dir = '/home/alexander/nlg-project/data/'

In [5]:
train_df['Poem'][1]

NameError: name 'train_df' is not defined

In [52]:
test_df = pd.read_csv(processed_data_dir + 'test_data.csv')
train_df = pd.read_csv(processed_data_dir + 'train_data.csv')
print(train_df)


        Unnamed: 0                                               Poem  \
0             7542  the mockingbird has testified\nto springs exis...   
1           116211  ive actually\nheld a black card in my hand\nan...   
2            31718  although alas the\ncoat on his back is a coat\...   
3            97130  these memories dont\nmean anything to you and\...   
4            97063  a mad old lady\nwhooped her tits out at me in\...   
...            ...                                                ...   
136820      133722  the manager hugged\nme like u back see i am\na...   
136821       50010  an entire plot\nbased around klaus tripping an...   
136822       96222  why cant paulina\nhave social media i\nmiss he...   
136823        5797  i feel used he said\nand old as usual\ni belie...   
136824       51245  tip if youre upset\ntake a walk or jog it off\...   

                   Title  
0       testified almond  
1              held card  
2        lining although  
3          memo

In [53]:
whole_df = pd.read_csv(processed_data_dir + 'kaggle_data.csv')

In [54]:
whole_df

Unnamed: 0             line_0                          line_1  \
0                0      fishing boats                       colors of   
1                1      ash wednesday              trying to remember   
2                2         snowy morn             pouring another cup   
3                3       shortest day                    flames dance   
4                4               haze           half the horse hidden   
...            ...                ...                             ...   
144022      144118  im not asking did          you say it nor clarify   
144023      144119    you are truly a              moron or a liar im   
144024      144120  aint no selfie on  this earth thats gonna make me   
144025      144121   is doing a great        job turning independents   
144026      144122   wanted to send a       quick follow up on if the   

                         line_2       source  valid  line_0_scount  \
0                   the rainbow  tempslibres   True              4   
1                      my dream  tempslibres   True              5   
2               of black coffee  tempslibres   True              3   
3                   in the oven  tempslibres   True              4   
4              behind the house  tempslibres   True              2   
...                         ...          ...    ...            ...   
144022    what you said neither       twaiku   True              7   
144023   inclined to think both       twaiku   True              7   
144024         like theresa may       twaiku   True              6   
144025           into democrats       twaiku   True              5   
144026  blood is loud talk soon       twaiku   True              6   

        line_1_scount  line_2_scount  
0                   3              3  
1                   6              2  
2                   7              6  
3                   5              5  
4                   7              6  
...               ...            ...  
144022             10              8  
144023              6              8  
144024             11              6  
144025              8              5  
144026              9              8  

[144027 rows x 9 columns]

In [55]:
def syllable_vec(row):
    return [row['line_0_scount'],row['line_1_scount'],row['line_2_scount']]

def change_title(row):
    #adds syllable info to title
    #print(row['Title'])
    return str(row['syllables']) + ';' + str(row['Title'])

In [56]:
def add_syllables_title(part_df, match_df):
    merged = pd.merge(part_df, match_df,how='left', left_on=['Unnamed: 0'], right_index=True)
    merged['syllables'] = merged.apply(syllable_vec,axis=1)
    merged.drop(columns=['Unnamed: 0_x', 'Unnamed: 0_y','line_0','line_1','line_2','source','valid','line_0_scount',
                        'line_1_scount','line_2_scount'],inplace=True)
    merged['Title'] = merged.apply(change_title,axis=1)
    
    return merged

In [57]:
train_df = add_syllables_title(train_df,whole_df)
test_df = add_syllables_title(test_df,whole_df)

In [58]:
train_df

Poem  \
0       the mockingbird has testified\nto springs exis...   
1       ive actually\nheld a black card in my hand\nan...   
2       although alas the\ncoat on his back is a coat\...   
3       these memories dont\nmean anything to you and\...   
4       a mad old lady\nwhooped her tits out at me in\...   
...                                                   ...   
136820  the manager hugged\nme like u back see i am\na...   
136821  an entire plot\nbased around klaus tripping an...   
136822  why cant paulina\nhave social media i\nmiss he...   
136823  i feel used he said\nand old as usual\ni belie...   
136824  tip if youre upset\ntake a walk or jog it off\...   

                               Title    syllables  
0       [10, 9, 11];testified almond  [10, 9, 11]  
1                [5, 9, 8];held card    [5, 9, 8]  
2          [6, 9, 5];lining although    [6, 9, 5]  
3           [7, 10, 7];memories mean   [7, 10, 7]  
4             [6, 12, 5];whooped pub   [6, 12, 5]  
...                              ...          ...  
136820      [7, 9, 7];hugged manager    [7, 9, 7]  
136821     [5, 10, 7];klaus tripping   [5, 10, 7]  
136822       [6, 8, 7];paulina maddy    [6, 8, 7]  
136823       [7, 5, 16];height usual   [7, 5, 16]  
136824             [8, 9, 8];jog tip    [8, 9, 8]  

[136825 rows x 3 columns]

NameError: name 'model_input' is not defined

In [62]:
max_input_length = 128
max_target_length = 128

def encode_sentences(tokenizer, in_df, max_input_length=max_input_length,max_target_length=max_target_length, pad_to_max_length=True, return_tensors="pt"):
  
  #Function that tokenizes a sentence 
   # Args: tokenizer - the BART tokenizer; source and target sentences are the source and target sentences
  #    Returns: Dictionary with keys: input_ids, attention_mask, target_ids
    source_sentences = [str(doc) for doc in in_df["Title"]]
    target_sentences = [str(doc) for doc in in_df["Poem"]]

    input_ids = []
    attention_masks = []
    target_ids = []
    tokenized_sentences = {}

    for sentence in source_sentences:
        encoded_dict = tokenizer(
          sentence,
          max_length=max_input_length,
          padding="max_length" if pad_to_max_length else None,
          truncation=True,
          return_tensors=return_tensors,
          add_prefix_space = True
      )

        input_ids.append(encoded_dict['input_ids'])
        attention_masks.append(encoded_dict['attention_mask'])

    input_ids = torch.cat(input_ids, dim = 0)
    attention_masks = torch.cat(attention_masks, dim = 0)

    for sentence in target_sentences:
        encoded_dict = tokenizer(
          sentence,
          max_length=max_target_length,
          padding="max_length" if pad_to_max_length else None,
          truncation=True,
          return_tensors=return_tensors,
          add_prefix_space = True
      )
    # Shift the target ids to the right
    # shifted_target_ids = shift_tokens_right(encoded_dict['input_ids'], tokenizer.pad_token_id)
        target_ids.append(encoded_dict['input_ids'])

    target_ids = torch.cat(target_ids, dim = 0)


    batch = {
      "input_ids": input_ids,
      "attention_mask": attention_masks,
      "labels": target_ids,
    }

    return batch



In [10]:
df["labels"].to_list()

KeyError: 'labels'

In [63]:
train_model = encode_sentences(tokenizer,train_df)
test_model = encode_sentences(tokenizer,test_df)

In [ ]:
test_model

In [65]:
train_ds = PoemDataset(train_model)
eval_ds = PoemDataset(test_model)

In [64]:
class PoemDataset(Dataset):
    def __init__(self, df):
        self.labels = df['labels']
        self.mask = df['attention_mask']
        self.input = df['input_ids']
        #self.target_transform = target_transform

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        
        input_ids = self.input[idx]
        attention_masks = self.mask[idx]
        target_ids = self.labels[idx]
        batch = {
          "input_ids": input_ids,
          "decoder_attention_mask": torch.tensor([1] * 128),
          "attention_mask": attention_masks,
          "label_ids": target_ids,
        }
        return batch

In [ ]:
class Collator_poem_gen(DataCollatorForSeq2Seq):
        
    def __call__(self, batch):
        input_ids_batch = []
        input_ids_len = []
        
        labels_batch = []
        labels_len = []
        
        for example in batch:
            input_ids = example["Title"]
            input_ids_len.append(len(input_ids))
            input_ids_batch.append(input_ids)
            
            labels = example["Poem"]
            labels_len.append(len(labels))
            labels_batch.append(labels)

        input_ids_padded = self.process_encoded_text(input_ids_batch, input_ids_len, self.tokenizer.pad_token_id)
        labels_padded = self.process_encoded_text(labels_batch, labels_len, self.label_pad_token_id)
        
        attention_mask = self.generate_attention_mask(input_ids_padded, self.tokenizer.pad_token_id)
        decoder_attention_mask = self.generate_attention_mask(labels_padded, self.tokenizer.pad_token_id)
        
        return {
            "input_ids": input_ids_padded,
            "attention_mask": attention_mask,
            "decoder_attention_mask": decoder_attention_mask,
            "labels": labels_padded,
        }

    def process_encoded_text(self, sequences, sequences_len, pad_token_id):
        sequences_max_len = np.max(sequences_len)
        max_length = min(sequences_max_len, self.max_length)
        padded_sequences = self.pad_sequences(sequences, max_length, pad_token_id)
        return torch.LongTensor(padded_sequences)

    def generate_attention_mask(self, input_ids, pad_token_id):
        return (input_ids != pad_token_id).long()
    
    def pad_sequences(self, sequences, max_length, pad_token_id):
        num_samples = len(sequences)
        padded_sequences = np.full((num_samples, max_length), pad_token_id)
        for i, sequence in enumerate(sequences):
            sequence = np.array(sequence)[:max_length]
            padded_sequences[i, :len(sequence)] = sequence
        return padded_sequences

In [99]:
from sklearn.model_selection import train_test_split

input_df = pd.DataFrame.from_dict(model_input)

ValueError: If using all scalar values, you must pass an index

In [66]:
batch_size = 16 

args = Seq2SeqTrainingArguments(
    "BART-base-syllable-naive",
    evaluation_strategy = "epoch",
    #learning_rate=2e-5,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size,
   # weight_decay=0.01,
   # save_total_limit=3,
   # num_train_epochs=1,
   # predict_with_generate=True,
    
    learning_rate=1e-4,
    weight_decay=0.01,
    adam_beta1=0.9,
    adam_beta2=0.999,
    adam_epsilon=1e-6,
    max_grad_norm=1.0,
    num_train_epochs=10,
    lr_scheduler_type="linear",
    warmup_ratio=0.1,
   # label_names="labels",
    #fp16=True,
  #  use_auth_token=False
    #push_to_hub=True,
)

In [67]:
#data_collator = Collator_poem_gen(tokenizer=tokenizer, max_length=512)
#train_ds = PoemDataset(model_input)
#eval_ds = PoemDataset(model_input)
trainer = Seq2SeqTrainer(
    model=model,
    args=args,
   # data_collator=data_collator,
    train_dataset=train_ds,
    
    eval_dataset=eval_ds,
    #use_auth_token=False,
    
    tokenizer=tokenizer
)

In [94]:
trainer

In [95]:
#!python -c "from huggingface_hub.hf_api import HfFolder; HfFolder.save_token('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')"


In [68]:
trainer.train()

/home/alexander/anaconda3/lib/python3.8/site-packages/transformers/optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
***** Running training *****
  Num examples = 136825
  Num Epochs = 10
  Instantaneous batch size per device = 16
  Total train batch size (w. parallel, distributed & accumulation) = 16
  Gradient Accumulation steps = 1
  Total optimization steps = 85520


Saving model checkpoint to BART-base-syllable-naive/checkpoint-500
Configuration saved in BART-base-syllable-naive/checkpoint-500/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-500/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-500/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-500/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-1000
Configuration saved in BART-base-syllable-naive/checkpoint-1000/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-1000/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-1000/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-1000/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-1500
Configuration saved in BART-base-syllable-naive/checkpoint-1500/config.json
Model weights saved in BART-base-

Saving model checkpoint to BART-base-syllable-naive/checkpoint-10500
Configuration saved in BART-base-syllable-naive/checkpoint-10500/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-10500/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-10500/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-10500/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-11000
Configuration saved in BART-base-syllable-naive/checkpoint-11000/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-11000/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-11000/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-11000/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-12000
Configuration saved in BART-base-syllable-naive/checkpoint-12000/config.json
Model weights sa

tokenizer config file saved in BART-base-syllable-naive/checkpoint-20500/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-20500/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-21000
Configuration saved in BART-base-syllable-naive/checkpoint-21000/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-21000/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-21000/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-21000/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-21500
Configuration saved in BART-base-syllable-naive/checkpoint-21500/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-21500/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-21500/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-21

Saving model checkpoint to BART-base-syllable-naive/checkpoint-30500
Configuration saved in BART-base-syllable-naive/checkpoint-30500/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-30500/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-30500/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-30500/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-31000
Configuration saved in BART-base-syllable-naive/checkpoint-31000/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-31000/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-31000/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-31000/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-31500
Configuration saved in BART-base-syllable-naive/checkpoint-31500/config.json
Model weights sa

tokenizer config file saved in BART-base-syllable-naive/checkpoint-40000/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-40000/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-40500
Configuration saved in BART-base-syllable-naive/checkpoint-40500/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-40500/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-40500/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-40500/special_tokens_map.json
Saving model checkpoint to BART-base-syllable-naive/checkpoint-41000
Configuration saved in BART-base-syllable-naive/checkpoint-41000/config.json
Model weights saved in BART-base-syllable-naive/checkpoint-41000/pytorch_model.bin
tokenizer config file saved in BART-base-syllable-naive/checkpoint-41000/tokenizer_config.json
Special tokens file saved in BART-base-syllable-naive/checkpoint-41

KeyboardInterrupt: 

In [69]:
trainer.evaluate()

***** Running Evaluation *****
  Num examples = 7202
  Batch size = 16


{'eval_loss': 0.40320608019828796}

In [16]:
trainer.plot()

AttributeError: 'Seq2SeqTrainer' object has no attribute 'plot'